spring:
  config:
    import: "aws-secretsmanager:petshop/prod"
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}

  jpa:
    hibernate:
      ddl-auto: none

toss:
  secret-key: ${tossSecretKey}
